# Generated by Django 4.2.3 on 2023-07-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
